import React, { useEffect, useState } from "react";
import axios from "axios";
import { ResponsiveContainer, PieChart, Pie, Cell, Tooltip, BarChart, Bar, CartesianGrid, XAxis, YAxis } from "recharts";

const CHART_COLORS = ["#2ad1a3", "#2cb5f8", "#ffd166", "#ff8a5b", "#8ec5ff", "#7c91ff", "#6fd4ff", "#63e6be"];
const BUDGET_COLORS = {
  "Budget Goal": "#2cb5f8",
  "Current Spend": "#ff8a5b",
  "Target Savings": "#2ad1a3",
  "Projected Savings": "#ffd166",
};

function MoneyDNA({ apiBaseUrl, authHeaders }) {
  const [data, setData] = useState(null);
  const [models, setModels] = useState([]);
  const [selectedModel, setSelectedModel] = useState("");
  const [income, setIncome] = useState("");
  const [goalPct, setGoalPct] = useState("20");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");

  const categoryData = Object.entries(data?.spending_per_category || {}).map(([name, value]) => ({
    name,
    value: Number(value || 0),
  }));
  const budgetData =
    data?.budget_goal !== null && data?.budget_goal !== undefined
      ? [
          { name: "Budget Goal", value: Number(data.budget_goal || 0) },
          { name: "Current Spend", value: Number(data.month_spending || 0) },
          { name: "Target Savings", value: Number(data.target_savings || 0) },
          { name: "Projected Savings", value: Number(data.expected_savings || 0) },
        ]
      : [];

  const loadMoneyDNA = async () => {
    setLoading(true);
    setError("");
    try {
      const params = selectedModel ? { model: selectedModel } : {};
      const [dnaRes, modelsRes] = await Promise.all([
        axios.get(`${apiBaseUrl}/money_dna`, { headers: authHeaders, params }),
        axios.get(`${apiBaseUrl}/blackboard/models`, { headers: authHeaders }),
      ]);
      const availableModels = modelsRes.data?.models || [];
      setModels(availableModels);
      if (!selectedModel && availableModels.length > 0) {
        setSelectedModel(availableModels[0].id);
      }
      const response = dnaRes;
      setData(response.data);
      const profile = response.data?.income_profile || {};
      setIncome(profile.monthly_income === null || profile.monthly_income === undefined ? "" : String(profile.monthly_income));
      setGoalPct(String(profile.savings_goal_pct || 20));
    } catch (err) {
      setError(err?.response?.data?.error || "Unable to load Money DNA.");
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadMoneyDNA();
  }, [apiBaseUrl, authHeaders, selectedModel]);

  const saveIncomeProfile = async (event) => {
    event.preventDefault();
    setError("");
    try {
      await axios.put(
        `${apiBaseUrl}/income_profile/current`,
        {
          monthly_income: parseFloat(income),
          savings_goal_pct: parseFloat(goalPct || "20"),
        },
        { headers: authHeaders }
      );
      await loadMoneyDNA();
    } catch (err) {
      setError(err?.response?.data?.error || "Failed to save income profile.");
    }
  };

  return (
    <div>
      <h2>Money DNA</h2>
      <p className="meta">AI-based spending behavior profile with benchmark comparisons and savings suggestions.</p>
      <div className="row-actions" style={{ marginBottom: 10 }}>
        <select
          value={selectedModel}
          onChange={(e) => setSelectedModel(e.target.value)}
          disabled={models.length === 0}
        >
          {models.length === 0 ? <option value="">No models</option> : null}
          {models.map((item) => (
            <option key={item.id} value={item.id}>
              {item.id}
            </option>
          ))}
        </select>
      </div>

      {loading ? <p className="meta">Loading Money DNA...</p> : null}
      {error ? <p className="meta">{error}</p> : null}

      {data ? (
        <>
          <p className="meta">Generated by: {data.generated_by || "local_rules"}</p>

          <h3>Income-Based Goal</h3>
          <form onSubmit={saveIncomeProfile}>
            <div className="summary-grid">
              <div>
                <div className="meta">Monthly Income</div>
                <input
                  type="number"
                  min="0"
                  step="0.01"
                  value={income}
                  onChange={(e) => setIncome(e.target.value)}
                  placeholder="e.g. 6000"
                />
              </div>
              <div>
                <div className="meta">Standard Savings Goal %</div>
                <input
                  type="number"
                  min="1"
                  max="89"
                  step="0.1"
                  value={goalPct}
                  onChange={(e) => setGoalPct(e.target.value)}
                  placeholder="20"
                />
              </div>
            </div>
            <button type="submit">Save Goal Settings</button>
          </form>

          {data.budget_goal !== null && data.budget_goal !== undefined ? (
            <div className="summary-grid" style={{ marginTop: 12 }}>
              <div className="expense-row">
                <div>
                  <div className="meta">Derived Budget Goal</div>
                  <strong>${Number(data.budget_goal || 0).toFixed(2)}</strong>
                </div>
              </div>
              <div className="expense-row">
                <div>
                  <div className="meta">Target Monthly Savings</div>
                  <strong>${Number(data.target_savings || 0).toFixed(2)}</strong>
                </div>
              </div>
              <div className="expense-row">
                <div>
                  <div className="meta">Budget Remaining (This Month)</div>
                  <strong>${Number(data.remaining_budget || 0).toFixed(2)}</strong>
                </div>
              </div>
              <div className="expense-row">
                <div>
                  <div className="meta">Projected Savings (This Month)</div>
                  <strong>${Number(data.expected_savings || 0).toFixed(2)}</strong>
                </div>
              </div>
            </div>
          ) : (
            <p className="meta">Set monthly income above to derive an AI budget goal automatically.</p>
          )}

          {data.budget_goal !== null && data.budget_goal !== undefined ? (
            <div className="chart-grid">
              <div className="chart-card">
                <h4>Budget vs Spend</h4>
                <div className="chart-box">
                  <ResponsiveContainer width="100%" height={280}>
                    <BarChart data={budgetData} layout="vertical" margin={{ left: 18, right: 14 }}>
                      <CartesianGrid strokeDasharray="3 3" stroke="rgba(147,168,208,0.2)" />
                      <XAxis type="number" stroke="#9fb0cf" />
                      <YAxis dataKey="name" type="category" stroke="#9fb0cf" width={125} />
                      <Tooltip formatter={(value) => `$${Number(value).toFixed(2)}`} />
                      <Bar dataKey="value" radius={[0, 8, 8, 0]}>
                        {budgetData.map((item) => (
                          <Cell key={`budget-${item.name}`} fill={BUDGET_COLORS[item.name] || "#2cb5f8"} />
                        ))}
                      </Bar>
                    </BarChart>
                  </ResponsiveContainer>
                </div>
                <div className="list" style={{ marginTop: 8 }}>
                  {budgetData.map((item) => (
                    <div className="expense-row" key={`legend-${item.name}`}>
                      <span>
                        <span
                          style={{
                            display: "inline-block",
                            width: 10,
                            height: 10,
                            borderRadius: 99,
                            marginRight: 8,
                            background: BUDGET_COLORS[item.name] || "#2cb5f8",
                          }}
                        />
                        {item.name}
                      </span>
                      <strong>${Number(item.value || 0).toFixed(2)}</strong>
                    </div>
                  ))}
                </div>
              </div>

              <div className="chart-card">
                <h4>Spending Allocation</h4>
                <div className="chart-box">
                  <ResponsiveContainer width="100%" height={280}>
                    <PieChart>
                      <Pie
                        data={categoryData}
                        dataKey="value"
                        nameKey="name"
                        cx="50%"
                        cy="50%"
                        outerRadius={90}
                        label
                      >
                        {categoryData.map((entry, index) => (
                          <Cell key={`dna-cat-${entry.name}`} fill={CHART_COLORS[index % CHART_COLORS.length]} />
                        ))}
                      </Pie>
                      <Tooltip formatter={(value) => `$${Number(value).toFixed(2)}`} />
                    </PieChart>
                  </ResponsiveContainer>
                </div>
              </div>
            </div>
          ) : null}

          <div className="summary-grid" style={{ marginTop: 12 }}>
            <div className="expense-row">
              <div>
                <div className="meta">Lifetime Spending</div>
                <strong>${Number(data.total_spending || 0).toFixed(2)}</strong>
              </div>
            </div>
            <div className="expense-row">
              <div>
                <div className="meta">Month ({data.month})</div>
                <strong>${Number(data.month_spending || 0).toFixed(2)}</strong>
              </div>
            </div>
          </div>

          <h3>DNA Signals</h3>
          {data.blackboard_comparisons?.length ? (
            <div className="list">
              {data.blackboard_comparisons.map((item, index) => (
                <div className="expense-row" key={`bb-compare-${index}`}>
                  <span>{item}</span>
                </div>
              ))}
            </div>
          ) : null}

          {data.comparisons?.length ? (
            <div className="list">
              {data.comparisons.map((item) => (
                <div className="expense-row" key={item.category}>
                  <div>
                    <strong>{item.category}</strong>
                    <div className="meta">{item.message}</div>
                  </div>
                  <div style={{ textAlign: "right" }}>
                    <div>User: {(Number(item.user_share || 0) * 100).toFixed(1)}%</div>
                    <div className="meta">Avg: {(Number(item.average_share || 0) * 100).toFixed(1)}%</div>
                  </div>
                </div>
              ))}
            </div>
          ) : (
            <p className="meta">No category comparison available yet.</p>
          )}

          <h3>Smart Recommendations</h3>
          {data.recommendations?.length ? (
            <div className="list">
              {data.recommendations.map((item, index) => (
                <div className="expense-row" key={`rec-${index}`}>
                  <span>{item}</span>
                </div>
              ))}
            </div>
          ) : (
            <p className="meta">No recommendations yet.</p>
          )}

          <h3>AI Narrative</h3>
          <div className="insight">{data.ai_narrative || "No AI narrative available."}</div>

          <h3>Blackboard Integration</h3>
          {data.provider_error ? (
            <p className="meta">{data.provider_error}</p>
          ) : (
            <div className="expense-row">
              <div>
                <div className="meta">Models Available</div>
                <strong>{Number(data.provider_info?.models_count || 0)}</strong>
              </div>
              <div style={{ textAlign: "right" }}>
                <div className="meta">Providers</div>
                <strong>{(data.provider_info?.providers || []).join(", ") || "N/A"}</strong>
              </div>
            </div>
          )}
        </>
      ) : null}
    </div>
  );
}

export default MoneyDNA;
